# Generated by Django 4.1.3 on 2022-11-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_NO', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('age', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('reg_NO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_info.student')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=20)),
                ('Presenty', models.IntegerField()),
                ('reg_NO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student_info.student')),
            ],
        ),
    ]
