# Generated by Django 4.1 on 2022-11-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_info', '0002_admission_marks_stu_feedback_student_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Date_Admission',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='branch',
            field=models.CharField(choices=[('MECH', 'MECH'), ('ELECTRICAL', 'ELECTRICAL'), ('CHEM', 'Chemical'), ('IT', 'IT'), ('CSE', 'CSE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stu_feedback',
            name='Subject',
            field=models.CharField(choices=[('TOC', 'TOC'), ('PYTHON', 'PYTHON'), ('SOFTWARE ENGINEERING', 'SOFTWARE ENGINEERING'), ('OS', 'OS'), ('DBMS', 'DBMS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
