# Generated by Django 4.1.3 on 2022-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_info', '0004_alter_admission_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Studentname',
            field=models.CharField(max_length=60),
        ),
    ]
